### ISSUE TITLE
Do not rewrite non-error responses

### ISSUE THREAD

**Issue by kirelagin** [epicallan/servant-errors#13]
The middleware rewrites responses with HTTP status codes > 200, which is an odd choice.

It definitely does not sound as a good idea to rewrite any of the Success (2xx) responses. Also, I am not sure about Redirection (3xx), I guess it would be better not to touch them too (especially 304 Not Modified, which is a fairly common response semantically equivalent to Success).

Given that the library is called `servant-errors`, I think, it would make perfect sense to rewrite only error responses, that is, 4xx and 5xx.

**Comment by epicallan** [comment]
This library was more geared to re-writing errors servant throws internally, these errors have no content type and have status codes greater than 200. The content-type criteria eliminate's would be false positives.

But I wouldn't mind restricting to 400 and 500 range to make things less confusing. Going to implement this.

**Comment by epicallan** [comment]
I have addressed this in a recently merged PR.
